### ISSUE TITLE
[SUGGESTION] Dynamic trees support

### ISSUE THREAD

**Issue by Sunconure11** [AstroInteractive/Traverse#1]
https://minecraft.curseforge.com/projects/dynamictrees

This mod replaces vanilla trees with ones that grow over time. There are plans for cross-compat. Would it be possible to add support for it?

**Comment by TheCodedOne** [comment]
I'll have to look into that one for probably Traverse 2

**Comment by ProfessorProspector** [comment]
I'm gonna say no on this one, not for Traverse 1. We can probably do this for Traverse 2 when we get that going. Traverse 1 is now feature-complete
