### ISSUE TITLE
[1.12.2] Model Loading errors

### ISSUE THREAD

**Issue by NotAVerb** [AstroInteractive/Traverse#11]
There are several model loading errors pertaining to the blue cobblestone in the startup logs.
Are there typos in the JSONs?
https://gist.github.com/NotAVerb/017a3954d5b90893465cefa17e514dc4

V1.3.1

Edit: The texture for the blue cobble double slab is busted
![2018-03-12_00 13 09](https://user-images.githubusercontent.com/30223331/37265518-cf6dd21c-25ab-11e8-905c-e9eb724d4707.png)

**Comment by ProfessorProspector** [comment]
Moved to https://github.com/TraverseTeam/Traverse/issues/12
