### ISSUE TITLE
Traverse compat - Better with mods "HCStump"

### ISSUE THREAD

**Issue by GeekyNinja** [AstroInteractive/Traverse#2]
G'day, have a question. Not an issue, per se, but wanted to get some feedback.

I'm running Traverse (v1.3.1) alongside Better With Mods (v2.0.10), and have "HCStumping", which "makes the bottom of trees into stumps which cannot be removed by hand".

Currently, your trees do not obey this rule, and was wondering if there is a way for your trees to have these "stumps" & obey the Stump rule set by BWM at all? I don't know if it would have to be set up on the BWM side or if it's set up on the Traverse side, hence why I'm here asking.

Thanks so much :-)

**Comment by TheCodedOne** [comment]
ask BWM, its their feature.
