### ISSUE TITLE
Crag Rock Stairs are Broken

### ISSUE THREAD

**Issue by WolfieWaffle** [AstroInteractive/Traverse#3]
My friend found this issue with crag rock stairs, and I think the other stairs as well. They don't place correctly. I have had this issue as well, just try placing the stairs in multiple orientations and they do not behave properly.

![2017-09-21_20 40 35](https://user-images.githubusercontent.com/8770485/30777397-dfe6845a-a076-11e7-917d-f8e9a5ef7612.png)
![cragstairsbroke](https://user-images.githubusercontent.com/8770485/30777398-dfe6e044-a076-11e7-9654-276fcb7914c9.png)

**Comment by TheCodedOne** [comment]
Hm, i'll look into this

**Comment by MarshalWren** [comment]
The block states for the stairs are off. I made quick resource pack that fixes it.

[Traverse-stair-patch.zip](https://github.com/AstroInteractive/Traverse/files/1563453/Traverse-stair-patch.zip)

**Comment by TheCodedOne** [comment]
Fixed in dev, will be in next update
