### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by phit** [AstroInteractive/Traverse#6]
https://github.com/AstroInteractive/Traverse/blob/3a26699b280bbc1bcf76b0d95aed3ed36c2aa94d/src/main/java/prospector/traverse/world/TraverseWorld.java#L73

should point at `disableSnowyConiferousForest`

---

https://github.com/AstroInteractive/Traverse/blob/2cb2a163ea74123f2b0cc05dcb20f7f162008ecc/src/main/java/prospector/traverse/world/biomes/BiomeGlacier.java#L55-L61

doesn't seem to work, both biomes return `-1` for `Biome.MUTATION_TO_BASE_ID_MAP.get(biome)`

---

lastly forge complains a bit
`[main/WARN] [FML]: No types have been added to Biome traverse:rocky_plateau, types have been assigned on a best-effort guess: [PLAINS]`

**Comment by TheCodedOne** [comment]
Will look into it and try fix for the next update, not sure what is up with the `Biome.MUTATION_TO_BASE_ID_MAP.get(biome)` though

**Comment by phit** [comment]
yeah I couldn't quite figure it out yet either, otherwise I would have made a PR.. I just noticed when trying to render a map using [this](https://github.com/phit/Pioneer/blob/v1.11.2/src/main/java/ttftcuts/pioneer/map/MapJob.java#L172) and it wouldn't give me the correct ID

**Comment by ProfessorProspector** [comment]
The hardest part of this issue is that the MCP mappings for a load of this stuff are so wrong/terrible. 

Also about the no types for rocky plateau...yeah. None of Forge's types seemed to describe the biome, so I didn't give it any. Kinda stupid that forge complains.

**Comment by TheCodedOne** [comment]
2 are fixed, moved the unfixed issue to ProfessorProspector/Traverse#9

**Comment by phit** [comment]
thanks
